### ISSUE TITLE
ERROR: Model provided has model identifier 'inpu', should be 'TFL3'

### ISSUE THREAD

**Issue by Hypfer** [synesthesiam/de_deepspeech-aashishag#2]
Unfortunately, even after fixing the download, this model doesn't seem to work at all.

Nothing is being recognized which isn't surprising considering these log contents:

```
[DEBUG:2021-01-04 20:59:10,677] rhasspyasr_deepspeech.transcribe: Loading model from /profiles/de/deepspeech/model/0.6.1/output_graph.pb (beam width=500)
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
ERROR: Model provided has model identifier 'inpu', should be 'TFL3'

Error at reading model file /profiles/de/deepspeech/model/0.6.1/output_graph.pb
[ERROR:2021-01-04 20:59:10,694] rhasspyasr_deepspeech_hermes: transcribe
Traceback (most recent call last):
  File "/usr/lib/rhasspy/rhasspy-asr-deepspeech-hermes/rhasspyasr_deepspeech_hermes/__init__.py", line 334, in transcribe
    transcription = self.transcriber.transcribe_wav(wav_bytes)
  File "/usr/lib/rhasspy/rhasspy-asr-deepspeech/rhasspyasr_deepspeech/transcribe.py", line 42, in transcribe_wav
    self.maybe_load_model()
  File "/usr/lib/rhasspy/rhasspy-asr-deepspeech/rhasspyasr_deepspeech/transcribe.py", line 139, in maybe_load_model
    self.model = deepspeech.Model(str(self.model_path), self.beam_width)
  File "/usr/lib/rhasspy/.venv/lib/python3.7/site-packages/deepspeech/__init__.py", line 42, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 12288
```

**Comment by synesthesiam** [comment]
This may be what you're looking for: https://github.com/rhasspy/rhasspy-profile/pull/1

**Comment by luyuaner** [comment]
Loading model from file deepspeech-0.9.3-models.pbmm
TensorFlow: v2.3.0-6-g23ad988fcd
DeepSpeech: v0.9.3-0-gf2e9c858
ERROR: Model provided has model identifier 'u/3?, should be 'TFL3'

Error at reading model file deepspeech-0.9.3-models.pbmm
Traceback (most recent call last):
  File "d:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python38\Scripts\deepspeech.exe\__main__.py", line 7, in <module>
  File "d:\python38\lib\site-packages\deepspeech\client.py", line 119, in main
    ds = Model(args.model)
  File "d:\python38\lib\site-packages\deepspeech\__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)

**Comment by TheMuhammadAdnan** [comment]
> Loading model from file deepspeech-0.9.3-models.pbmm TensorFlow: v2.3.0-6-g23ad988fcd DeepSpeech: v0.9.3-0-gf2e9c858 ERROR: Model provided has model identifier 'u/3?, should be 'TFL3'
> 
> Error at reading model file deepspeech-0.9.3-models.pbmm Traceback (most recent call last): File "d:\python38\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "d:\python38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\python38\Scripts\deepspeech.exe__main__.py", line 7, in File "d:\python38\lib\site-packages\deepspeech\client.py", line 119, in main ds = Model(args.model) File "d:\python38\lib\site-packages\deepspeech__init__.py", line 38, in **init** raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status)) RuntimeError: CreateModel failed with 'Failed to initialize memory mapped model.' (0x3000)

@luyuaner I'm also facing the same issue, how you resolve it?
